/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/admin/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Вход сотрудника. Refresh-токен — в httpOnly cookie. */
        post: operations["Auth_signIn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Обновить access-токен по refresh cookie (ротация) */
        post: operations["Auth_refreshSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Auth_signOut"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Auth_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/auth/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Auth_changeOwnPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Users_list"];
        put?: never;
        post: operations["Users_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Users_roles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["Users_update"];
        trace?: never;
    };
    "/api/v1/admin/users/{id}/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["Users_roles_"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{id}/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Users_reset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/branches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AdminBranches_list"];
        put?: never;
        post: operations["AdminBranches_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/branches/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AdminBranches_get"];
        put: operations["AdminBranches_update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/legal-entities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["LegalEntities_list"];
        put?: never;
        post: operations["LegalEntities_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/legal-entities/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["LegalEntities_update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/system/audit-log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["System_auditLog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/system/integrations/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["System_integrationCatalog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/system/integrations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["System_integrations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/system/integrations/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["System_saveIntegration"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/system/integration-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["System_integrationLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/system/failed-jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["System_failed"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/system/failed-jobs/{id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["System_retry"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/system/failed-jobs/{id}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["System_resolve"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/branches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PublicBranches_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/branches/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PublicBranches_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        LoginDto: {
            /** @example owner@aula.kz */
            email: string;
            password: string;
        };
        SessionDto: {
            accessToken: string;
            /** @description Время жизни access-токена, секунд */
            expiresIn: number;
            mustChangePassword: boolean;
        };
        RoleAssignmentDto: {
            /** @enum {string} */
            role: "branch_operator" | "banquet_manager" | "branch_manager" | "content_manager" | "finance" | "owner" | "sysadmin";
            /** @description Филиал для филиальных ролей; null для глобальных */
            branchId?: Record<string, never> | null;
        };
        MeDto: {
            id: string;
            name: string;
            email: string;
            mustChangePassword: boolean;
            roles: components["schemas"]["RoleAssignmentDto"][];
            /** @description Права во всех филиалах */
            globalPermissions: string[];
            branchPermissions: {
                [key: string]: string[];
            };
            /** @description Филиалы, доступные пользователю (для переключателя) */
            branchIds: string[];
        };
        ChangePasswordDto: {
            currentPassword: string;
            newPassword: string;
        };
        StaffUserDto: {
            id: string;
            email: string;
            name: string;
            phone?: Record<string, never> | null;
            telegramChatId?: Record<string, never> | null;
            isActive: boolean;
            mustChangePassword: boolean;
            lastLoginAt?: Record<string, never> | null;
            /** Format: date-time */
            createdAt: string;
            roles: components["schemas"]["RoleAssignmentDto"][];
        };
        StaffUsersPageDto: {
            items: components["schemas"]["StaffUserDto"][];
            total: number;
            page: number;
            perPage: number;
        };
        RoleDefinitionDto: {
            role: string;
            /** @enum {string} */
            scope: "branch" | "global";
            title: Record<string, never>;
            permissions: string[];
        };
        CreateUserDto: {
            email: string;
            name: string;
            phone?: Record<string, never> | null;
            telegramChatId?: Record<string, never> | null;
            /** @description Если не задан — будет сгенерирован временный пароль */
            password?: string;
            roles: components["schemas"]["RoleAssignmentDto"][];
        };
        CreatedUserDto: {
            user: components["schemas"]["StaffUserDto"];
            /** @description Показывается один раз */
            temporaryPassword?: Record<string, never> | null;
        };
        UpdateUserDto: {
            email?: string;
            name?: string;
            phone?: Record<string, never> | null;
            telegramChatId?: Record<string, never> | null;
            isActive?: boolean;
        };
        SetRolesDto: {
            roles: components["schemas"]["RoleAssignmentDto"][];
        };
        TemporaryPasswordDto: {
            temporaryPassword: string;
        };
        TranslatableDto: {
            /** @description Қазақша */
            kk?: string;
            /** @description Русский */
            ru?: string;
            /** @description English (опционально) */
            en?: string;
        };
        GeoPointDto: {
            /** @example 51.1282 */
            lat: number;
            /** @example 71.4304 */
            lng: number;
        };
        BranchSettingsDto: {
            acceptsDelivery?: boolean;
            acceptsPickup?: boolean;
            acceptsReservations?: boolean;
            deliveryLeadMinutes?: number;
            pickupLeadMinutes?: number;
            maxScheduleDaysAhead?: number;
            /** @enum {string} */
            stopListMode?: "hide" | "mark_unavailable";
            paymentMethods?: ("online" | "on_receipt")[];
            awaitingPaymentTimeoutMinutes?: number;
            requirePhoneVerificationForOnReceipt?: boolean;
            requirePhoneVerificationForReservations?: boolean;
            staffNotifyPhone?: Record<string, never> | null;
            staffTelegramChatId?: Record<string, never> | null;
        };
        BranchDto: {
            id: string;
            code: string;
            slug: string;
            name: components["schemas"]["TranslatableDto"];
            address: components["schemas"]["TranslatableDto"];
            location: components["schemas"]["GeoPointDto"];
            phone: string;
            whatsapp?: Record<string, never> | null;
            email?: Record<string, never> | null;
            timezone: string;
            openingHours: Record<string, never>;
            settings: components["schemas"]["BranchSettingsDto"];
            legalEntityId?: Record<string, never> | null;
            isActive: boolean;
            sortOrder: number;
        };
        BranchInputDto: {
            /**
             * @description Код для номеров документов
             * @example GL
             */
            code: string;
            /** @example greenline */
            slug: string;
            name: components["schemas"]["TranslatableDto"];
            address: components["schemas"]["TranslatableDto"];
            location: components["schemas"]["GeoPointDto"];
            phone: string;
            whatsapp?: Record<string, never> | null;
            email?: Record<string, never> | null;
            /** @default Asia/Almaty */
            timezone: string;
            /**
             * @description Часы работы по дням: { mon: [{ open: "10:00", close: "23:00" }], ... }
             * @example {
             *       "mon": [
             *         {
             *           "open": "10:00",
             *           "close": "23:00"
             *         }
             *       ]
             *     }
             */
            openingHours: Record<string, never>;
            settings?: components["schemas"]["BranchSettingsDto"];
            legalEntityId?: Record<string, never> | null;
            isActive?: boolean;
            sortOrder?: number;
        };
        LegalEntityDto: {
            /** @example ТОО «Express kitchen» */
            name: string;
            /** @example Express kitchen */
            shortName: string;
            /** @example 000000000000 */
            bin: string;
            legalAddress: string;
            actualAddress?: Record<string, never> | null;
            directorName: string;
            /** @example Директор */
            directorPosition: string;
            /** @example Устава */
            actingBasis: string;
            bankName: string;
            /** @example KZ000000000000000000 */
            iban: string;
            bik: string;
            /** @example 17 */
            kbe: string;
            vatPayer: boolean;
            /** @description Ставка НДС, базисные пункты (1600 = 16%) */
            vatRateBp: number;
            vatCertificate?: Record<string, never> | null;
            phone?: Record<string, never> | null;
            email?: Record<string, never> | null;
            isDefault?: boolean;
            id: string;
        };
        LegalEntityInputDto: {
            /** @example ТОО «Express kitchen» */
            name: string;
            /** @example Express kitchen */
            shortName: string;
            /** @example 000000000000 */
            bin: string;
            legalAddress: string;
            actualAddress?: Record<string, never> | null;
            directorName: string;
            /** @example Директор */
            directorPosition: string;
            /** @example Устава */
            actingBasis: string;
            bankName: string;
            /** @example KZ000000000000000000 */
            iban: string;
            bik: string;
            /** @example 17 */
            kbe: string;
            vatPayer: boolean;
            /** @description Ставка НДС, базисные пункты (1600 = 16%) */
            vatRateBp: number;
            vatCertificate?: Record<string, never> | null;
            phone?: Record<string, never> | null;
            email?: Record<string, never> | null;
            isDefault?: boolean;
        };
        IntegrationSettingDto: {
            key: string;
            enabled: boolean;
            config: {
                [key: string]: unknown;
            };
            /** @description Маскированные секреты */
            secrets: {
                [key: string]: string;
            };
            updatedAt?: Record<string, never> | null;
        };
        SaveIntegrationSettingDto: {
            enabled: boolean;
            config: {
                [key: string]: unknown;
            };
            /** @description Новые значения секретов; пустая строка или null — удалить; отсутствие ключа — оставить прежнее */
            secrets?: {
                [key: string]: string | null;
            };
        };
        PublicBranchDto: {
            id: string;
            slug: string;
            name: components["schemas"]["TranslatableDto"];
            address: components["schemas"]["TranslatableDto"];
            location: components["schemas"]["GeoPointDto"];
            phone: string;
            whatsapp?: Record<string, never> | null;
            timezone: string;
            openingHours: Record<string, never>;
            isOpenNow: boolean;
            acceptsDelivery: boolean;
            acceptsPickup: boolean;
            acceptsReservations: boolean;
            paymentMethods: string[];
            stopListMode: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    Auth_signIn: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDto"];
                };
            };
        };
    };
    Auth_refreshSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDto"];
                };
            };
        };
    };
    Auth_signOut: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    Auth_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeDto"];
                };
            };
        };
    };
    Auth_changeOwnPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordDto"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    Users_list: {
        parameters: {
            query?: {
                q?: string;
                role?: string;
                branchId?: string;
                page?: string;
                perPage?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StaffUsersPageDto"];
                };
            };
        };
    };
    Users_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatedUserDto"];
                };
            };
        };
    };
    Users_roles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleDefinitionDto"][];
                };
            };
        };
    };
    Users_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StaffUserDto"];
                };
            };
        };
    };
    Users_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StaffUserDto"];
                };
            };
        };
    };
    Users_roles_: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetRolesDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StaffUserDto"];
                };
            };
        };
    };
    Users_reset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemporaryPasswordDto"];
                };
            };
        };
    };
    AdminBranches_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BranchDto"][];
                };
            };
        };
    };
    AdminBranches_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BranchInputDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BranchDto"];
                };
            };
        };
    };
    AdminBranches_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BranchDto"];
                };
            };
        };
    };
    AdminBranches_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BranchInputDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BranchDto"];
                };
            };
        };
    };
    LegalEntities_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LegalEntityDto"][];
                };
            };
        };
    };
    LegalEntities_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LegalEntityInputDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LegalEntityDto"];
                };
            };
        };
    };
    LegalEntities_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LegalEntityInputDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LegalEntityDto"];
                };
            };
        };
    };
    System_auditLog: {
        parameters: {
            query?: {
                actorUserId?: string;
                action?: string;
                entityType?: string;
                entityId?: string;
                branchId?: string;
                from?: string;
                to?: string;
                page?: string;
                perPage?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    System_integrationCatalog: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    System_integrations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntegrationSettingDto"][];
                };
            };
        };
    };
    System_saveIntegration: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveIntegrationSettingDto"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    System_integrationLogs: {
        parameters: {
            query?: {
                integration?: string;
                correlationId?: string;
                success?: string;
                page?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    System_failed: {
        parameters: {
            query?: {
                open?: string;
                page?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    System_retry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    System_resolve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PublicBranches_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicBranchDto"][];
                };
            };
        };
    };
    PublicBranches_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicBranchDto"];
                };
            };
        };
    };
}
